version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=captchaRedisPassword
      - LOG_LEVEL=INFO
    volumes:
      - ./logs:/app/logs
      - ./model:/app/model
    restart: unless-stopped

  redis:
    image: redis:6.2
    command: redis-server --requirepass captchaRedisPassword
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  redis_data: 